# logic/parameter_docs.py

parameter_docs = {
    "height": "Height of the layer in nanometers.",
    "panelDensity": "Panel density used in meshing calculations (in 1/nm²).",
    "localWaveCalcType": "Wave calculation type: classical, quantum, or none.",
    "materialType": "Material assigned to the layer.",
    "name": "User-defined layer name for identification.",
    "dielectricConstant": "Relative dielectric constant of the material.",
    "effectiveMass_x": "Effective mass along X direction.",
    "effectiveMass_y": "Effective mass along Y direction.",
    "effectiveMass_z": "Effective mass along Z direction.",
    "bandShift": "Energy band shift in eV.",
    "backgroundDopingDensity": "Doping density in cm⁻³.",
    "Output parameters": "Controls output-related parameters.",
    "Self consistent iteration": "Defines self-consistency loop tolerances.",
    "Stabilized RK": "Runge-Kutta method stabilization parameters.",
    "Girf flag": "Grid refinement flag.",
    "Plot flag": "Enable plotting of results.",
    "Thread count": "Number of CPU threads used.",
    "Self consistency flag": "Enable self-consistency.",
    "Base": "Base bias value.",
    "Upper screen": "Upper screening potential.",
    "Lower screen": "Lower screening potential.",
    "Lect accumulation": "Left accumulation gate voltage.",
    "P1": "Plunger gate 1 voltage.",
    "P2": "Plunger gate 2 voltage.",
    "Right accumulation": "Right accumulation gate voltage.",
    "BLA1": "Barrier gate A1 voltage.",
    "B12": "Barrier gate 12 voltage.",
    "b2RA": "Barrier 2 Right Accumulation voltage.",
    "Top Bias 1d": "Top bias in 1D simulations.",
    "Bias offset": "Offset applied to all gate biases.",
    "Gate Geo2dFile Name": "2D gate geometry file name.",
    "Xpanel density": "Panel density along X.",
    "Ypanel density": "Panel density along Y.",
    "Fft quantizatoin flag": "Enable FFT quantization.",
    "Gate smoothing flag": "Enable gate smoothing.",
    "Layered structure": "Contains all layer definitions.",
    "Layer": "Single layer block.",
    "Base location": "Reference base location.",
    "Uniform q well grid flag": "Enable uniform grid in quantum well.",
    "Masking parameters": "Defines subdomain masking parameters.",
    "Subdomain flags": "Flags controlling subdomain behavior.",
    "Sub domain interpolation": "Interpolation settings for subdomains.",
    "Sub domain smoothing": "Smoothing parameters for subdomains.",
    "Material": "Material block.",
    "Output file name": "Output file path.",
    "Ece path": "Executable path.",
    "Derivative perturbation size": "Perturbation size for derivatives.",
    "Tuning tolerance": "Tolerance for auto-tuning.",
    "Output alpha matrix": "Enable output of alpha matrix.",
    "export auto tune flag": "Enable exporting auto-tune state.",
    "Import auto tune flag": "Enable importing auto-tune state.",
    "Auto tune file name": "Auto-tune file path.",
    "Recreate initial state": "Recreate initial auto-tuning state.",
    "Effective bc flag": "Enable effective boundary conditions.",
    "Effective bc interface index": "Index for interface boundary condition.",
    "Effective bc data file": "Data file for effective BC.",
    "Ebc modes x": "Effective BC modes along X.",
    "Ebc modes y": "Effective BC modes along Y.",
    "Gated interface src": "Gated interface source value.",
    "Delta factor": "Delta factor in smoothing.",
    "Minimal delta": "Minimum delta value in smoothing.",
    "Minimal delta flag": "Enable minimal delta value.",
    "Mollifier diff": "Mollifier differentiation order.",
    "Mollifier order": "Mollifier polynomial order.",
    "Refine degree": "Refinement degree.",
    "Refine factor": "Refinement factor.",
    "Richardson type": "Type of Richardson extrapolation.",
    "Cap gate dist": "Capacitor gate distance.",
    "Cap material name": "Material name for capacitor.",
    "cap z panel density": "Z panel density in capacitor.",
    "Interface bc flag": "Enable interface BC.",
    "Surface src density": "Surface source density.",
    "Uppercat type": "Type of upper cap.",
}  # IN REVIEW