# logic/parameter_docs.py

class ParameterDocs:
    @staticmethod
    def get(param_name):
        return ParameterDocs.get(param_name, f"No documentation found for {param_name}.")

ParameterDocs = {
    "height": "Height of the layer in nanometers.",
    "panelDensity": "Panel density used in meshing calculations (in 1/nm²).",
    "localWaveCalcType": "Wave calculation type: classical, quantum, or none.",
    "materialType": "Material assigned to the layer.",
    "name": "User-defined layer name for identification.",
    "dielectricConstant": "Relative dielectric constant of the material.",
    "effectiveMass_x": "Effective mass along X direction.",
    "effectiveMass_y": "Effective mass along Y direction.",
    "effectiveMass_z": "Effective mass along Z direction.",
    "bandShift": "Energy band shift in eV.",
    "backgroundDopingDensity": "Doping density in cm⁻³.",
    "Output parameters": "Controls output-related parameters.",
    "Self consistent iteration": "Defines self-consistency loop tolerances.",
    "Stabilized RK": "Runge-Kutta method stabilization parameters.",
    "Girf flag": "Grid refinement flag.",
    "Plot flag": "Enable plotting of results.",
    "Thread count": "Number of CPU threads used.",
    "Self consistency flag": "Enable self-consistency.",
    "Base": "Base bias value.",
    "Upper screen": "Upper screening potential.",
    "Lower screen": "Lower screening potential.",
    "Lect accumulation": "Left accumulation gate voltage.",
    "P1": "Plunger gate 1 voltage.",
    "P2": "Plunger gate 2 voltage.",
    "Right accumulation": "Right accumulation gate voltage.",
    "BLA1": "Barrier gate A1 voltage.",
    "B12": "Barrier gate 12 voltage.",
    "b2RA": "Barrier 2 Right Accumulation voltage.",
    "Top Bias 1d": "Top bias in 1D simulations.",
    "Bias offset": "Offset applied to all gate biases.",
    "Gate Geo2dFile Name": "2D gate geometry file name.",
    "Xpanel density": "Panel density along X.",
    "Ypanel density": "Panel density along Y.",
    "Fft quantizatoin flag": "Enable FFT quantization.",
    "Gate smoothing flag": "Enable gate smoothing.",
    "Layered structure": "Contains all layer definitions.",
    "Layer": "Single layer block.",
    "Base location": "Reference base location.",
    "Uniform q well grid flag": "Enable uniform grid in quantum well.",
    "Masking parameters": "Defines subdomain masking parameters.",
    "Subdomain flags": "Flags controlling subdomain behavior.",
    "Sub domain interpolation": "Interpolation settings for subdomains.",
    "Sub domain smoothing": "Smoothing parameters for subdomains.",
    "Material": "Material block.",
    "Output file name": "Output file path.",
    "Ece path": "Executable path.",
    "Derivative perturbation size": "Perturbation size for derivatives.",
    "Tuning tolerance": "Tolerance for auto-tuning.",
    "Output alpha matrix": "Enable output of alpha matrix.",
    "export auto tune flag": "Enable exporting auto-tune state.",
    "Import auto tune flag": "Enable importing auto-tune state.",
    "Auto tune file name": "Auto-tune file path.",
    "Recreate initial state": "Recreate initial auto-tuning state.",
    "Effective bc flag": "Enable effective boundary conditions.",
    "Effective bc interface index": "Index for interface boundary condition.",
    "Effective bc data file": "Data file for effective BC.",
    "Ebc modes x": "Effective BC modes along X.",
    "Ebc modes y": "Effective BC modes along Y.",
    "Gated interface src": "Gated interface source value.",
    "Delta factor": "Delta factor in smoothing.",
    "Minimal delta": "Minimum delta value in smoothing.",
    "Minimal delta flag": "Enable minimal delta value.",
    "Mollifier diff": "Mollifier differentiation order.",
    "Mollifier order": "Mollifier polynomial order.",
    "Refine degree": "Refinement degree.",
    "Refine factor": "Refinement factor.",
    "Richardson type": "Type of Richardson extrapolation.",
    "Cap gate dist": "Capacitor gate distance.",
    "Cap material name": "Material name for capacitor.",
    "cap z panel density": "Z panel density in capacitor.",
    "Interface bc flag": "Enable interface BC.",
    "Surface src density": "Surface source density.",
    "Uppercat type": "Type of upper cap.",

#double checked these down here
    "RunParameters": "Main simulation control settings including output, solver tolerances, stabilization parameters, threading, and self-consistency.",
    "OutputParameters": "Settings related to the amount and type of output generated.",
    "stateOutputCountMax": "Maximum number of states to output during simulation.",
    "waveFunSquaredPlotFlag": "Enables plotting of wave function squared values.",
    "SelfConsistentIteration": "Tolerance settings for self-consistent field iterations.",
    "SCstopTolerance": "Convergence tolerance for self-consistent field iterations.",
    "StabilizedRK": "Runge-Kutta integrator configuration including step size and stabilization options.",
    "RKinitTimestep": "Initial timestep size for Runge-Kutta integration.",
    "RKmaxSteps": "Maximum number of Runge-Kutta steps allowed.",
    "RKdegree": "Degree/order of the Runge-Kutta integrator.",
    "verboseOutputFlag": "Enables detailed logging of Runge-Kutta steps.",
    "gridFlag": "Toggles use of grid refinement.",
    "plotFlag": "Enables plotting during simulation.",
    "threadCount": "Number of CPU threads used for computation.",
    "selfConsistencyFlag": "Enables self-consistent field iteration.",
    "AutoTuningData": "Auto-tuning simulation configuration file paths, perturbation sizes, and tolerances.",
    "tuningInputFileName": "File name containing input data for auto-tuning.",
    "outputFileName": "Output file where auto-tuning results are saved.",
    "ExePath": "Path to the executable used for running auto-tuning simulations.",
    "DerivativePertubationSize": "Size of perturbation applied when calculating derivatives.",
    "TuningTolerance": "Convergence tolerance for the auto-tuning algorithm.",
    "OutputAlphaMatrix": "Enables output of the alpha matrix used in auto-tuning.",
    "ImportExportAutoTuningState": "Flags and file paths for saving or loading auto-tuning simulation states.",
    "exportAutoTuneFlag": "Enables exporting the auto-tune state to a file.",
    "importAutoTuneFlag": "Enables importing a saved auto-tune state from a file.",
    "autoTuneFileName": "File name used to save or load auto-tune binary data.",
    "recreateInitialState": "Recreates the initial state of auto-tuning upon loading.",
    "AutoTuningInput": "Definitions for auto-tuning input parameters such as gate types.",
    "inputType": "Specifies the type of input control, e.g., plunger gate.",
    "AutoTuningOutput": "Auto-tuning target values and output types for each domain.",
    "targetValue": "Target value for auto-tuning in the specified domain.",
    "outputType": "Defines the type of output measured, e.g., local energy.",
    "relatedPlungerGate": "Specifies which plunger gate is related to the output.",
    "EffectiveBC": "Effective boundary condition flags and parameters.",
    "effectiveBCflag": "Enables or disables effective boundary conditions.",
    "effectiveBCinterfaceIndex": "Interface index used for applying effective boundary conditions.",
    "effectiveBCdataFile": "File containing data used for effective boundary conditions.",
    "EBCmodesX": "Number of effective boundary condition modes along X.",
    "EBCmodesY": "Number of effective boundary condition modes along Y.",
    "EffectiveBC_Parameters": "Numerical parameters for effective boundary condition sources.",
    "parameterValue": "Value assigned to the effective boundary condition source.",
    "parameterUnits": "Units associated with the parameter value, e.g., ChargePerCM^2.",
    "GateBias": "Bias voltage settings applied to various gates.",
    "Base": "Base bias voltage applied uniformly.",
    "UpperScreen": "Upper screen gate voltage.",
    "LowerScreen": "Lower screen gate voltage.",
    "LeftAccumulation": "Left accumulation gate voltage.",
    "P1": "Plunger gate 1 voltage.",
    "P2": "Plunger gate 2 voltage.",
    "RightAccumulation": "Right accumulation gate voltage.",
    "BLA1": "Barrier gate A1 voltage.",
    "B12": "Barrier gate 12 voltage.",
    "B2RA": "Barrier 2 right accumulation voltage.",
    "topBias1d": "Top bias voltage in 1D configuration.",
    "biasOffset": "Offset applied to all gate bias voltages.",
    "TransverseParameters": "Parameters for transverse meshing and 2D geometry.",
    "gateGeo2dFileName": "File name of 2D gate geometry.",
    "xPanelDensity": "Panel density along the X-axis.",
    "yPanelDensity": "Panel density along the Y-axis.",
    "FFTquantizationFlag": "Enables FFT quantization for transverse calculations.",
    "gateSmoothingFlag": "Enables smoothing in gate geometry.",
    "GateSmoothingParameters": "Mesh smoothing parameters for gate regions.",
    "deltaFactor": "Delta factor used in smoothing algorithm.",
    "minimalDelta": "Minimum delta value in smoothing.",
    "minimalDeltaFlag": "Enables usage of a minimum delta value.",
    "mollifierDiff": "Order of mollifier differentiation.",
    "mollifierOrder": "Polynomial order of the mollifier.",
    "refineDegree": "Degree of mesh refinement.",
    "refineFactor": "Refinement factor applied to the mesh.",
    "richardsonType": "Type of Richardson extrapolation applied.",
    "InterfaceBCparameters": "Interface boundary condition settings.",
    "capGateDist": "Distance from capacitor gate.",
    "capMaterialName": "Material used for the capacitor.",
    "capZpanelDensity": "Z-direction panel density in capacitor.",
    "interfaceBCflag": "Flag to enable interface boundary conditions.",
    "surfaceSrcDensity": "Surface source density applied.",
    "upperCapType": "Type of upper capacitor configuration.",
    "LowerSurfaceBoundaryConditions": "Boundary conditions applied to the lower surface.",
    "bias": "Bias voltage applied at the boundary.",
    "botBiasType": "Type of bias applied to the bottom boundary.",
    "NoiseSources": "Defines noise sources such as dipole sources.",
    "dirX": "Dipole orientation in the X direction.",
    "dirY": "Dipole orientation in the Y direction.",
    "dirZ": "Dipole orientation in the Z direction.",
    "strength": "Strength of the dipole noise source.",
    "xPos": "X position of the dipole.",
    "yPos": "Y position of the dipole.",
    "zPos": "Z position of the dipole.",
    "dipolePanelFactor": "Panel factor applied to the dipole.",
    "ImportExportSPiterate": "Import/export settings for self-consistent iterate states.",
    "exportPhiStarFlag": "Enable export of phi-star values.",
    "importPhiStarFlag": "Enable import of phi-star values.",
    "phiStarFileName": "File name for phi-star values.",
    "CreateInitialSPiterate": "Parameters for creating initial iterate states.",
    "calculationType": "Type of calculation performed.",
    "createInitialIterateFlag": "Flag to create initial iterate state.",
    "refinementFactor": "Factor by which the mesh is refined.",
    "SP_Parameters": "Single-particle simulation parameters.",
    "energyTransitionDelta": "Energy delta used in transitions.",
    "fermiLevel": "Fermi level setting.",
    "PoissonSolver_NumericalParameters": "Numerical parameters for the Poisson solver.",
    "ZapproxOrder": "Order of Z-direction approximation.",
    "iterativeInterfaceBC": "Enables iterative interface boundary conditions.",
    "verboseInterfaceBC": "Enables detailed output for interface boundary conditions."
,
    "SingleParticleEigensystemParameters": "Configuration for single-particle eigensystem solver parameters.",
    "maxDegeneracy": "Maximum degeneracy allowed in the eigensystem.",
    "subspaceTol": "Tolerance for subspace iterations.",
    "xyOpOrder": "Order of operator approximation in XY plane.",
    "zBasisSize": "Size of the Z-basis used in calculations.",
    "zSplineDegree": "Spline degree used for Z-direction basis.",
    "zSplinePanelDensity": "Panel density for Z-direction spline.",
    "verboseEigFlag": "Enable verbose output for eigensystem solver.",
    "stopCondition": "Condition used to stop eigensystem iterations.",
    "MultiDomainParameters": "Configuration settings for managing multiple computational domains.",
    "Masking_Parameters": "Settings for domain masking and transition width.",
    "relativeTransitionWidth": "Transition width relative to mesh size in masking.",
    "SubdomainFlags": "Flags that control subdomain behavior.",
    "excludedPotentialType": "Type of potential excluded in subdomains.",
    "snapBoundariesToGridFlag": "Flag to snap subdomain boundaries to the computational grid.",
    "SubdomainInterpolation": "Interpolation settings for subdomain mesh.",
    "degreeX": "Interpolation degree along X-axis.",
    "degreeY": "Interpolation degree along Y-axis.",
    "degreeZ": "Interpolation degree along Z-axis.",
    "SubdomainSmoothing": "Settings for smoothing within subdomains.",
    "densitySmoothing": "Flag to enable density smoothing in subdomains.",
    "deltaXmeshFactor": "Mesh refinement factor along X-axis.",
    "deltaYmeshFactor": "Mesh refinement factor along Y-axis.",
    "ComputationalSubdomains": "Defines global and individual computational subdomain parameters.",
    "GlobalSubdomain": "Parameters for the global computational subdomain.",
    "fixedChargeFlag": "Flag to enable fixed charge in subdomain.",
    "fixedChargeValue": "Fixed charge value applied in subdomain.",
    "occupancy": "Number of occupied states in subdomain.",
    "maskSubdomainsFlag": "Flag to enable subdomain masking.",
    "additionalMaskCharge": "Additional charge applied in masked subdomain.",
    "maskedDensityFraction": "Fraction of density masked in subdomain.",
    "domainXmin": "Minimum X-coordinate value of subdomain.",
    "domainXmax": "Maximum X-coordinate value of subdomain.",
    "domainYmin": "Minimum Y-coordinate value of subdomain.",
    "domainYmax": "Maximum Y-coordinate value of subdomain.",
    "domainBarrierFlag": "Flag indicating if barrier exists within subdomain.",
    "globalSubdomainMaskType": "Type of mask applied globally in subdomain.",
    "subdomainLinkedFlag": "Flag to link subdomains together.",
    "TunnelingRateCalculation": "Parameters for calculating tunneling rates between subdomains.",
    "tunnelCalcPlotFlag": "Flag to enable plotting during tunneling rate calculation.",
    "P1P2dot": "Parameters specific to tunneling between P1 and P2 domains.",
    "computeRateFlag": "Flag to enable rate computation for specified domains.",
    "subdomainA": "First subdomain used in tunneling calculation.",
    "subdomainB": "Second subdomain used in tunneling calculation.",
    "barrierGate": "Gate used as a barrier in tunneling calculations.",
    "ExcludedPotentialCalculation": "Settings for excluding potentials in subdomains.",
    "PIP2_FCI": "Configuration for excluding potential between P1 and P2 subdomains.",
    "createPotentialFlag": "Flag to enable creation of excluded potential.",
    "subdomain_1": "First subdomain in excluded potential calculation.",
    "subdomain_2": "Second subdomain in excluded potential calculation.",
    "PI_FCI": "Configuration for excluding potential in P1 subdomain only.",
    "P2_FCI": "Configuration for excluding potential in P2 subdomain only.",

"MaterialDataSource": "Specifies the source for material parameters used in the simulation.",
    "materialSource": "Defines which material list to use as input for material properties.",
    "LayeredStructure": "Defines the full structure of layers in the simulation, including materials and geometries.",
    "Layer": "Single layer definition within a layered structure.",
    "name": "User-defined name for the layer or material.",
    "materialType": "Material assigned to the specific layer.",
    "height": "Height of the layer in simulation units.",
    "panelDensity": "Density of panels used in mesh calculations.",
    "localWaveCalcType": "Type of wavefunction calculation to use (classical, quantum, or none).",
    "baseLocation": "Base location reference point for the layered structure.",
    "uniformQwellGridFlag": "Enables uniform grid distribution in quantum well regions.",
    "MaterialList": "Defines the list of all materials and their physical properties.",
    "Material": "Single material entry in the material list.",
    "dielectricConstant": "Relative permittivity of the material.",
    "effectiveMass_x": "Effective mass of carriers along the X axis.",
    "effectiveMass_y": "Effective mass of carriers along the Y axis.",
    "effectiveMass_z": "Effective mass of carriers along the Z axis.",
    "bandShift": "Energy band shift value in eV.",
    "backgroundDopingDensity": "Doping density of the material.",
    "backgroundDopingDensityOrig": "Original doping density value before adjustments." 
}
  # IN REVIEW